namespace NodeJS {
    interface ProcessEnv {
        NEXT_PUBLIC_CLOUDINARY_BASE_URL: string
        NEXT_PUBLIC_CLOUDINARY_VIDEO_BASE_URL: string
        NEXT_PUBLIC_CLOUDINARY_FOLDER: string
    
        NEXT_PUBLIC_BASE_URL: string
        NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: string
    
        NEXT_PUBLIC_CLOUDINARY_API_KEY: string
        NEXT_PUBLIC_CLOUDINARY_API_SECRET: string
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string
    
        NEXT_PUBLIC_CLOUDINARY_BASE_URL: string
        NEXT_PUBLIC_CLOUDINARY_VIDEO_BASE_URL: string
        NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: string
        NEXT_PUBLIC_CLOUDINARY_API_KEY: string
        NEXT_PUBLIC_CLOUDINARY_API_SECRET: string
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string
        NEXT_PUBLIC_CLOUDINARY_FOLDER: string
    }
}